# Generated by Django 3.0.1 on 2020-05-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('descriprion', models.CharField(max_length=200, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('dish_type', models.CharField(choices=[('pizza', 'Pizza'), ('burger', 'Burger'), ('pasta', 'Pasta'), ('drink', 'Drink')], max_length=200, verbose_name='Type')),
                ('img', models.ImageField(upload_to='dishs/', verbose_name='Image')),
            ],
        ),
    ]
