# Generated by Django 3.0.1 on 2020-05-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook_room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='descriprion',
            new_name='description',
        ),
    ]
