# Generated by Django 3.0.1 on 2020-05-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_room', '0002_auto_20200516_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='small_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Small description'),
        ),
    ]
