# Generated by Django 3.0.1 on 2020-05-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_room', '0004_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='to_main_page',
            field=models.BooleanField(blank=True, default=False, verbose_name='To Main Page'),
            preserve_default=False,
        ),
    ]
